global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'flutterdevs9@gmail.com'
  smtp_auth_username: 'flutterdevs9@gmail.com'
  smtp_auth_password: 'bllyhrqghvjuvvae'
  smtp_require_tls: true

route:
  receiver: 'default-receiver'
  group_by: ['alertname', 'job', 'team']
  
 
  group_wait: 10s       # Wait only 10s before sending the first batch
  group_interval: 15s   # Wait only 15s before sending updates/new alerts in the same group
  repeat_interval: 1m   # Default repeat for anything else

  routes:
    # ==========================================
    # ROUTING FOR BACKEND TEAM
    # ==========================================
    - matchers:
        - team="backend"
      routes:
        - matchers:
            - escalation_tier="l1_developer"
          receiver: 'backend-dev-email'
          repeat_interval: 1m # Quick reminder for testing
        
        - matchers:
            - escalation_tier="l2_team_lead"
          receiver: 'backend-lead-email'
          repeat_interval: 1m
          
        - matchers:
            - escalation_tier="l3_manager"
          receiver: 'backend-manager-email'
          repeat_interval: 1m
          
        - matchers:
            - escalation_tier="l4_cto"
          receiver: 'backend-cto-email'
          repeat_interval: 1m


    - matchers:
        - team="dba"
      routes:
        - matchers:
            - escalation_tier="l1_developer"
          receiver: 'dba-dev-email'
          repeat_interval: 1m
        
        - matchers:
            - escalation_tier="l2_team_lead"
          receiver: 'dba-lead-email'
          repeat_interval: 1m
          
        - matchers:
            - escalation_tier="l3_manager"
          receiver: 'dba-manager-email'
          repeat_interval: 1m
          
        - matchers:
            - escalation_tier="l4_cto"
          receiver: 'dba-cto-email'
          repeat_interval: 1m

  
    - matchers:
        - team="infra"
      routes:
        - matchers:
            - escalation_tier="l1_developer"
          receiver: 'infra-dev-email'
          repeat_interval: 1m
        
        - matchers:
            - escalation_tier="l2_team_lead"
          receiver: 'infra-lead-email'
          repeat_interval: 1m
          
        - matchers:
            - escalation_tier="l3_manager"
          receiver: 'infra-manager-email'
          repeat_interval: 1m
          
        - matchers:
            - escalation_tier="l4_cto"
          receiver: 'infra-cto-email'
          repeat_interval: 1m

receivers:
- name: default-receiver
  email_configs:
    - to: "flutterdevs9@gmail.com"
      send_resolved: true

- name: 'backend-dev-email'
  email_configs:
  - to: 'flutterdevs9@gmail.com'
    send_resolved: true

- name: 'backend-lead-email'
  email_configs:
  - to: 'flutterdevs9@gmail.com, sahil260605@gmail.com' 
    send_resolved: true
    headers:
      Subject: 'L2 ESCALATION (Backend): {{ .GroupLabels.alertname }}'

- name: 'backend-manager-email'
  email_configs:
  - to: 'sahilgarg@techmutant.com, flutterdevs9@gmail.com, sahil260605@gmail.com' 
    send_resolved: true
    headers:
      Subject: 'L3 ESCALATION (Backend): {{ .GroupLabels.alertname }}'

- name: 'backend-cto-email'
  email_configs:
  - to: 'sahilgarg2606@gmail.com, flutterdevs9@gmail.com, sahil260605@gmail.com, sahilgarg@techmutant.com' 
    send_resolved: true
    headers:
      Subject: 'L4 CRITICAL (Backend): {{ .GroupLabels.alertname }}'


- name: 'dba-dev-email'
  email_configs:
  - to: 'flutterdevs9@gmail.com'
    send_resolved: true

- name: 'dba-lead-email'
  email_configs:
  - to: 'flutterdevs9@gmail.com, sahil260605@gmail.com'
    send_resolved: true
    headers:
      Subject: 'L2 ESCALATION (Database): {{ .GroupLabels.alertname }}'

- name: 'dba-manager-email'
  email_configs:
  - to: 'sahilgarg@techmutant.com, flutterdevs9@gmail.com, sahil260605@gmail.com' 
    send_resolved: true
    headers:
      Subject: 'L3 ESCALATION (Database): {{ .GroupLabels.alertname }}'

- name: 'dba-cto-email'
  email_configs:
  - to: 'sahilgarg2606@gmail.com, flutterdevs9@gmail.com, sahil260605@gmail.com, sahilgarg@techmutant.com' 
    send_resolved: true
    headers:
      Subject: 'L4 CRITICAL (Database): {{ .GroupLabels.alertname }}'


- name: 'infra-dev-email'
  email_configs:
  - to: 'flutterdevs9@gmail.com'
    send_resolved: true

- name: 'infra-lead-email'
  email_configs:
  - to: 'flutterdevs9@gmail.com, sahil260605@gmail.com'
    send_resolved: true
    headers:
      Subject: 'L2 ESCALATION (Infra): {{ .GroupLabels.alertname }}'

- name: 'infra-manager-email'
  email_configs:
  - to: 'flutterdevs9@gmail.com, sahil260605@gmail.com, sahilgarg@techmutant.com' 
    send_resolved: true
    headers:
      Subject: 'L3 ESCALATION (Infra): {{ .GroupLabels.alertname }}'

- name: 'infra-cto-email'
  email_configs:
  - to: 'sahilgarg2606@gmail.com, flutterdevs9@gmail.com, sahil260605@gmail.com, sahilgarg@techmutant.com' 
    send_resolved: true
    headers:
      Subject: 'L4 CRITICAL (Infra): {{ .GroupLabels.alertname }}'