global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  # - alerts.yml
  - test_rules.yml
scrape_configs:

  # Prometheus monitors itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  # Linux Host Metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
      
  - job_name: "blackbox-exporter"
    static_configs:
      - targets: ["blackbox-exporter:9115"]

  # Docker Container Metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
  # API Health Check - Invoice API
  - job_name: "invoice-api"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://invoice.nyife.chat/api/v1/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: blackbox-exporter:9115

  # API Health Check - Backend API
  - job_name: "backend-api"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://backend.nyife.chat/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: blackbox-exporter:9115